[project]
name = "tuw-informationvisualization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "cdsapi>=0.7.7",
    "geopandas>=1.1.1",
    "pandas>=2.3.3",
    "pygrib>=2.1.8",
]
